import type { NextPage } from 'next'
import Head from 'next/head'
import HeaderDesck from '../components/HeaderHomeDesk/headerDesck'
import HeaderMobile from '../components/HeaderHomeMobile/headerMobile'

import HomeImg from "../assets/home.svg"

import {Container} from "../styles/Home"
import Image from 'next/image'
import Link from 'next/link'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Container>
          <header>
          <HeaderDesck/>
          <HeaderMobile/>
          </header>
          <main>
            <div>
              <h1>Finance Plataform</h1>
              <p>Controle suas finanças de um jeito prático e fácil </p>
              <Link href="/signup">Inscreva-se já</Link>
            </div>
            <Image src={HomeImg} alt="Finance Control" />
         </main>
      </Container>
    </div>
  )
}

export default Home
